/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-120303-ga218cafe4d-20250718"
#endif /* AVUTIL_FFVERSION_H */
